### ISSUE TITLE
ImportError: No module named 'qiniustorage'

### ISSUE THREAD

**Issue by frankzhuo** [mtianyan/mtianyanSearch#2]
需要自己注册个七牛云吗

**Comment by frankzhuo** [comment]
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/admin/anaconda/lib/python3.5/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/Users/admin/anaconda/lib/python3.5/site-packages/django/utils/deprecation.py", line 95, in __call__
    response = self.get_response(request)
  File "/Users/admin/anaconda/lib/python3.5/site-packages/django/core/handlers/exception.py", line 37, in inner
    response = response_for_exception(request, exc)
  File "/Users/admin/anaconda/lib/python3.5/site-packages/django/core/handlers/exception.py", line 87, in response_for_exception
    response = handle_uncaught_exception(request, get_resolver(get_urlconf()), sys.exc_info())
  File "/Users/admin/anaconda/lib/python3.5/site-packages/django/core/handlers/exception.py", line 126, in handle_uncaught_exception
    return callback(request, **param_dict)
  File "/Users/admin/anaconda/lib/python3.5/site-packages/django/utils/decorators.py", line 142, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/Users/admin/anaconda/lib/python3.5/site-packages/django/views/defaults.py", line 75, in server_error
    return HttpResponseServerError(template.render())
  File "/Users/admin/anaconda/lib/python3.5/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/Users/admin/anaconda/lib/python3.5/site-packages/django/template/base.py", line 175, in render
    return self._render(context)
  File "/Users/admin/anaconda/lib/python3.5/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
  File "/Users/admin/anaconda/lib/python3.5/site-packages/django/template/base.py", line 943, in render
    bit = node.render_annotated(context)
  File "/Users/admin/anaconda/lib/python3.5/site-packages/django/template/base.py", line 910, in render_annotated
    return self.render(context)
  File "/Users/admin/anaconda/lib/python3.5/site-packages/django/templatetags/static.py", line 106, in render
    url = self.url(context)
  File "/Users/admin/anaconda/lib/python3.5/site-packages/django/templatetags/static.py", line 103, in url
    return self.handle_simple(path)
  File "/Users/admin/anaconda/lib/python3.5/site-packages/django/templatetags/static.py", line 118, in handle_simple
    return staticfiles_storage.url(path)
  File "/Users/admin/anaconda/lib/python3.5/site-packages/django/utils/functional.py", line 215, in inner
    self._setup()
  File "/Users/admin/anaconda/lib/python3.5/site-packages/django/contrib/staticfiles/storage.py", line 494, in _setup
    self._wrapped = get_storage_class(settings.STATICFILES_STORAGE)()
  File "/Users/admin/anaconda/lib/python3.5/site-packages/django/core/files/storage.py", line 356, in get_storage_class
    return import_string(import_path or settings.DEFAULT_FILE_STORAGE)
  File "/Users/admin/anaconda/lib/python3.5/site-packages/django/utils/module_loading.py", line 17, in import_string
    module = import_module(module_path)
  File "/Users/admin/anaconda/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 985, in _gcd_import
  File "<frozen importlib._bootstrap>", line 968, in _find_and_load
  File "<frozen importlib._bootstrap>", line 943, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 985, in _gcd_import
  File "<frozen importlib._bootstrap>", line 968, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
ImportError: No module named 'qiniustorage'
